#=======Color=====#
N = '\033[0m'    # Normal Color
Y = '\033[1;33m' # Yellow Color
R = '\033[1;31m' # Red Color
G = '\033[1;32m' # Green Color
W = '\033[1;37m' # White Color
D = '\033[1;9;31m'  # DelBold Color
#==================#
import os
import sys
import time
os.system("clear")
print("%s================================================%s" % (R,N))
print("%s----------------Tools For Termux----------------%s" % (G,N))
print("%s================================================%s" % (R,N))
print('''%s
     ████████╗███████╗████████╗
     ╚══██╔══╝██╔════╝╚══██╔══╝
        ██║   █████╗     ██║   
        ██║   ██╔══╝     ██║   
        ██║   ██║        ██║   
        ╚═╝   ╚═╝        ╚═╝     %s''' % (G,N))                      
print("%s================================================%s" % (R,N))
print("%s----------Coded By Imperior Hackers-----------%s" % (Y,N))
print("%s================================================%s" % (R,N))
print("%s================================================%s" % (R,N))
time.sleep(5)
print("%s================================================%s" % (R,N))
print("%sInstalling Basic Packages%s" % (G,N))
print("%s================================================%s" % (R,N))
time.sleep(3)
os.system("apt update && apt upgrade")
os.system("pkg install python -y")
os.system("pkg install python2 -y")
os.system("pkg install ruby -y") 
os.system("pkg install git -y")
os.system("pkg install screenfetch -y")
os.system("pkg install cowsay -y")
os.system("pkg install toilet -y")
os.system("pkg install figlet -y")
print("%s===========================================%s" % (R,N))
print("%sInstallation Done Please Wait...%s" % (G,N))
print("%s===========================================%s" % (R,N))
print("")
time.sleep(3)
print("")
print("%s===========================================%s" % (R,N))
print("%sInstalling Networking Packages%s" % (G,N))
print("%s===========================================%s" % (R,N))
time.sleep(3)
os.system("pkg install php -y")
os.system("pkg install perl -y")
os.system("pkg install nmap -y")
os.system("pkg install openssh -y")
os.system("pkg install bash -y")
os.system("pkg install clang -y")
os.system("pkg install jq -y")
os.system("pkg install macchanger -y")
print("%s===========================================%s" % (R,N))
print("%sInstallation Done Please Wait...%s" % (G,N))
print("%s===========================================%s" % (R,N))
print("")
time.sleep(3)
print("")
print("%s===========================================%s" % (R,N))
print("%sInstalling Some More Important Packages%s" % (G,N))
print("%s===========================================%s" % (R,N))
time.sleep(3)
os.system("pkg install nano -y")
os.system("pkg install curl -y")
os.system("pkg install tar -y")
os.system("pkg install zip -y")
os.system("pkg install fish -y")
os.system("pkg install unzip -y")
os.system("pkg install tor -y")
os.system("pkg install sudo -y")
os.system("pkg install wget -y")
os.system("pkg install tor -y")
os.system("pkg install w3m -y")
os.system("pkg install cmatrix -y")
os.system("pkg install wcalc -y") 
os.system("pkg install openssl")
os.system("pkg install bmon -y")
print("%s========================================================%s" % (R,N))
print("%sInstallation Done Please Subscribe to Imperior Hackers%s" % (G,N))
print("%s========================================================%s" % (R,N))
print("")
time.sleep(3)
print("")
print("%s===========================================%s" % (R,N))
print("%sPlease Restart Your Termux%s" % (Y,N))
print("%s===========================================%s" % (R,N))
time.sleep(2)
os.system("exit")